import { useState } from "react"
import Head from "next/head"
import SearchBar from "../components/SearchBar"
import PaginatedCampaigns from "../components/PaginatedCampaigns";

export default function Home() {
  const [query, setQuery] = useState({});

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchBar className="w-50" search={setQuery} />
        <PaginatedCampaigns query={query} />
      </main>
    </>
  )
}
